services:
  # Backend API Service
  - type: web
    name: solana-ai-trader-api
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SOLANA_RPC_URL
        value: https://api.mainnet-beta.solana.com
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        sync: false
    
  # Frontend Static Site
  - type: web
    name: solana-ai-trader-frontend
    env: static
    buildCommand: "echo 'No build needed'"
    staticPublishPath: ./frontend
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html